### ISSUE TITLE
./show_metadata_tree_sizes.py crash

### ISSUE THREAD

**Issue by arvidjaar** [knorrie/python-btrfs#17]
10:/home/bor/python-btrfs/examples # ./show_metadata_tree_sizes.py /
Traceback (most recent call last):
  File "./show_metadata_tree_sizes.py", line 61, in <module>
    for extent in fs.extents(min_vaddr, max_vaddr, load_metadata_refs=True):
  File "/home/bor/python-btrfs/examples/btrfs/ctree.py", line 771, in extents
    extent = MetaDataItem(header, data, load_refs=load_metadata_refs)
  File "/home/bor/python-btrfs/examples/btrfs/ctree.py", line 1431, in __init__
    self._load_refs(data[ExtentItem._extent_item.size:])
  File "/home/bor/python-btrfs/examples/btrfs/ctree.py", line 1441, in _load_refs
    self.tree_block_refs._append(InlineTreeBlockRef(inline_ref_offset))
AttributeError: 'list' object has no attribute '_append'
10:/home/bor/python-btrfs/examples # rpm -q python3
python3-3.7.2-2.2.x86_64

openSUSE Tumbleweed

On commit b9da6522e2dba51a1b6ea56375f91817e8b2b431

**Comment by knorrie** [comment]
Ouch. No, a python list obviously has no _append method.

Apparently the filesystems I tested with don't hit these lines of code. That's interesting.

I added a small fix to the develop branch. Would you mind trying it?

**Comment by knorrie** [comment]
Aha, both of those filesystems are created a long time ago and were never converted to use "skinny metadata"... That's why they don't hit the MetaDataItem class.

This also impacts simply dumping metadata with e.g. dump_tree.py and extent level metadata blockgroup images in btrfs-heatmap.

**Comment by knorrie** [comment]
So, I did `btrfstune -x` on the filesystem of my main development vm, and there it is:

All of these now crash here in the same way (without the fix):
* `./show_metadata_tree_sizes.py /`
*  `./show_block_group_contents.py 287200772096 /`
* `btrfs-heatmap --blockgroup 287200772096 /`

**Comment by arvidjaar** [comment]
OK, for the sake of completeness - yes, development branch fixed it. BTW you can add "Fixes issue-number" to commit message or pull request and issue will be closed automatically when it is merged. Is also good for documentation :) See https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by knorrie** [comment]
Yeah, but I don't like a clone of a repo starting to do things in another place. But, I just tested. I can use closes: <full https://github/whrawhaw> to just make it act on these ones, so that's nice.

**Comment by knorrie** [comment]
FYI, because this is just too ugly to be true, I included it in an unblock request for Debian Buster:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925306

Fingers crossed! :)
