### ISSUE TITLE
How can I change the UUID of a snapshot?

### ISSUE THREAD

**Issue by ceremcem** [knorrie/python-btrfs#37]
Hi. I can't find a proper function to change the UUID of a snapshot. How can we change the UUID of a snaphot?

**Comment by knorrie** [comment]
Hi ceremcem,

There is no kernel API function for a running file system to change the UUID of a subvolume, so the fact that you cannot find it is right.

Hans

**Comment by ceremcem** [comment]
Okay, thanks for the answer. I'll request this feature in the mailing list.
