### ISSUE TITLE
Support for block-group-tree

### ISSUE THREAD

**Issue by hhoffstaette** [knorrie/python-btrfs#42]
The new block-group-tree support in 6.1 is :rainbow: awesomesauce :rainbow:.
Currently it still needs to be explicitly enabled when building progs (via `--enable-experimental`), but it *really* works as advertised and cuts mount times to practically zero.

An unfortunate side effect is that this feature is not recognized by python-btrfs:
```
Traceback (most recent call last):
  File "/usr/local/bin/btrfs-debugfs", line 12, in <module>
    bg = fs.block_group(chunk.vaddr, chunk.length)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/btrfs/ctree.py", line 874, in block_group
    raise ItemNotFoundError("No block group at vaddr {}".format(vaddr))
btrfs.ctree.ItemNotFoundError: No block group at vaddr 1928125743104
```

Recognizing this feature would be super lovely.

**Comment by knorrie** [comment]
Yes!

**Comment by knorrie** [comment]
Hi! Today I've been working on this. The changes can be found in the develop branch.

Have fun playing around with it. Looking forward to the feedback!

**Comment by hhoffstaette** [comment]
Working perfectly! Thanks! :100:

**Comment by hhoffstaette** [comment]
I think this can be closed - the block-group-tree support works fine, I haven't found any bugs whatsoever. Would be nice to see this merged to main branch. Thanks!

**Comment by hhoffstaette** [comment]
Reopening so that the issue becomes visible.

**Comment by hhoffstaette** [comment]
@knorrie Can you please merge this to the master branch so that we can close this properly?
The code has been working fine for months.

**Comment by knorrie** [comment]
Hi @hhoffstaette . Yes, thanks for pushing this.

I have cleaned things up a bit, removing some TEMP and WIP stuff, tested the Block Group Tree changes myself again and wrote the v14 changelog. It's in the develop branch now.

Tomorrow I'll do some sanity checks, check if the documentation changes look right and then tag and merge it.

**Comment by knorrie** [comment]
Done! \o/

**Comment by ErrorNoInternet** [comment]
Could we have a release on PyPi please 👀

**Comment by knorrie** [comment]
Yes! Done. v14.1 with the Warning fix included. And now I have to repair my sbuild stuff so I can do the Debian package as well.

**Comment by knorrie** [comment]
Slowly I'm getting things back on track... :D

I just uploaded 14.1-1 to Debian unstable!
https://tracker.debian.org/news/1556435/accepted-python-btrfs-141-1-source-into-unstable/
