### ISSUE TITLE
Misleading show_file.py error for non-regular file

### ISSUE THREAD

**Issue by arvidjaar** [knorrie/python-btrfs#6]
v8

```
linux-gtrk:/host/home/src/python-btrfs/examples # ./show_file.py /etc
/etc is not a filename!
linux-gtrk:/host/home/src/python-btrfs/examples # 
```

Well, it is obviously filename (in the broad sense of Unix), it is just filename of a file for which show_file cannot return information. Probably "not a regular file" or similar would be more clear; even better would be to actually return information that is possible in this case. Thanks.

**Comment by knorrie** [comment]
Yes, changing it in "is not a regular file!" would definitely be better. Fixed in develop branch.

Thanks for testing and reporting this.
